import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import LeftBar from "./components/LeftBar";
import RightBar from "./components/RightBar";
import Image from "next/image";
import { GenerationProvider } from "./context/GenerationContext";

const myFont = localFont({
  src: '../public/font/Minecraft.ttf',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body className={`text-xl antialiased min-h-screen `}>
        <div className="fixed inset-0 -z-20">
          <Image src="/rayquaza-gc45z3v2qfkovf8z.jpg" alt="background" fill priority className="object-cover -z-10 fixed inset-0"/>
        </div>
        <div className=" inset-0 bg-black/40 -z-10 fixed" />
        <div className="relative flex">
        <GenerationProvider>
          <LeftBar/>
          {children}
        </GenerationProvider>
        <RightBar/>
        </div>
      </body>
    </html>
  );
}
